version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - .:/go/src/dev/hello-world
    command: revel run dev/hello-world
